name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: mirrord-agent-ci

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
    - run: sudo apt install libpcap-dev
    - run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: sudo apt install -y libpcap-dev
    - run: sudo /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test
