name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
    - run: sudo apt install libpcap-dev
    - run: cargo clippy -- -D warnings

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
      with:
        container-runtime: containerd
    - name: Deploy required resources
      run: kubectl apply -f e2e/app.yaml
    - name: Build image
      run: |
        minikube image build --push -t mirrord:0.0.0 .
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Python dependencies 
      run: |
        pip install -r e2e/requirements.txt
    - name: Run test script
      run: |
        python e2e/main.py $(minikube service nginx --url)
