name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: mirrord-agent-ci

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
    - run: sudo apt install libpcap-dev
    - run: cargo clippy -- -D warnings

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
      with:
        container-runtime: containerd
    - name: Deploy required resources
      run: kubectl apply -f e2e/app.yaml
    # minikube with containerd doesn't like loading local images, so we push remote..
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_SHA
        docker push $IMAGE_ID:$GITHUB_SHA
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Python dependencies 
      run: |
        pip install -r e2e/requirements.txt
    - name: Run test script
      run: |
        python e2e/main.py $(minikube service nginx --url)
